version: 0.2

env:
  parameter-store:

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  pre_build:
    commands:
      - dotnet restore Code/LegoImageCreator.csproj
  build:
    commands:
      dotnet build Code/LegoImageCreator.csproj